### PR TITLE
Attempt to merge facebook/buck master into buck-tiger-team

### PR DESCRIPTION
**Pull request by dfed**

### CODE REVIEW

**Comment by ljharb** [comment]
It might be easier to push directly to master (to keep it in sync with the source) and set a different branch as th default for this fork (that you’d PR changes into)

**Comment by dfed** [comment]
Agreed. I mostly put this out to figure out how hard it would be to reply our changes over our fork – looks like it'd be pretty darned simple.

It looks like our `master` has no additional changes vs fb's `master`. I'll:
1. Update our `master` as you suggest
1. Re-target this PR against `buck-tiger-team` with a base of our `master`

**Comment by dfed** [comment]
Ugh. I didn't mean to merge that... but, no harm no foul I guess since I'm the only one using this branch thus far 😬

**Comment by ljharb** [comment]
Also we can update the default branch in settings so PRs and pushes default to track that instead of master.

**Pull request merged**
